### ISSUE TITLE
Acabar el juego!

### ISSUE THREAD

**Issue by nasivuela** [Adalab/dorcas-s2-evaluacion-intermedia-mariviru#1]
Tienes que repasar:

- las estructuras de control
- como definir y como ejecutar funciones
- como interactuar con el DOM.

A darle caña a ese juego!!! 
Te dejo un guión con pasos a seguir ;)

```
// Guardar la referencia a todos los elementos del DOM que vamos a usar en variables

// Generar el número aleatorio
// Y guardarlo en una variable

// Inicializar a 0 una variable de contador

// Crear una función que se ejecute cuando haga click en el botón de prueba
//  Esta función tiene que hacer:
//  1 - incrementar el contador
//  2 - y pintar el contador en mi html

//  3 - recoger el valor del input
//  4 - Compararlo con mi número aleatorio
//    - Si son iguales -> pintar el mensaje de "Ganadora"
//    - Si es menor -> pintar el mensaje de "te has quedado corta"
//    - Si es mayor -> pintar el mensaje de "te has pasado"

// Asignar un listener al botón de prueba para que ejecute una función al hacer click
```

**Comment by mariviru** [comment]
Vale, creo que ya está el juego, parece que funciona y se muestran los mensajes y el contador en el html.
Aún queda ponerlo bonito jeje

**Comment by nasivuela** [comment]
Buen trabajo @mariviru !

Un detallito: en la linea 10 has puesto `var userNumber = input.value;` y no parece que luego estés usando ese valor para nada... Igualmente en la función `showNumber` podrías hacer un logear el vaor del input directamente sin asignarlo a ninguna variable, ya que no parece que la uses después para nada más.

**Comment by mariviru** [comment]
Hecho, después de la explicación de ayer lo voy entendiendo mejor

**Comment by nasivuela** [comment]
Como estás a tope, te dejo un extra para cuando tengas un rato:

BONUS extra: ¿Que pasaría si la usuaria pone un valor númerico mayor que 100 o menor que 1? ¿Podriamos recordarle que el número secreto está entre 100 y 1? ;)

**Comment by mariviru** [comment]
Ya he puesto la condición que me pides y además he hecho que salga un mensaje si la usuaria no introduce ningún número :)

**Comment by nasivuela** [comment]
Ole @mariviru !!!
![](https://media.giphy.com/media/F6PFPjc3K0CPe/giphy.gif)
